#!/usr/bin/env bash
# worktree.sh — per-agent isolated worktree setup/teardown for /workflow-execute.
# Factors out the boilerplate from docs/ui-audit/HANDOFF.md (symlink .venv/.env/node_modules).
#
# Usage:
#   worktree.sh up   <agentslug> <plan-slug> [--ui]   # create worktree + branch + isolated TEST_DB
#   worktree.sh down <agentslug> [--force]            # GUARDED remove (refuses to lose work)
#   worktree.sh path <agentslug>                       # print the worktree path
#   worktree.sh testdb <agentslug>                     # print this worktree's TEST_DB_NAME
set -uo pipefail

CMD="${1:?up|down|path|testdb}"
SLUG="${2:?agentslug}"
ROOT="$(git rev-parse --show-toplevel)"
REPO="$(basename "$ROOT")"
WT="$(dirname "$ROOT")/${REPO}-${SLUG}"

# Per-worktree test DB name. Adversarial #4 / o3: conftest._derive_test_db_name() only isolates
# `feat/*` branches; worktree branches are `wf/<plan>/<slug>`, so without an explicit TEST_DB_NAME
# every wf/* worktree falls back to the SHARED `ticket_ocr_test` → two agents run `alembic upgrade`
# on one DB → version-table race, dirty schema, false green from leaked schema. Derive a UNIQUE name.
_sanitise() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '_'; }
SAFE_SLUG="$(_sanitise "$SLUG")"
TEST_DB_NAME="ticket_ocr_test_${SAFE_SLUG}"
TEST_DB_NAME="${TEST_DB_NAME:0:60}"

# Per-worktree Redis DB index + S3 bucket prefix (o3 review #8: TEST_DB isolated Postgres, but two
# parallel agents/stacks could still smash the SAME Redis logical DB or the SAME localstack/S3 bucket
# → cross-task state bleed + false green. Derive a STABLE per-slug Redis db number (0-15) from the
# slug hash, and a per-slug S3 bucket prefix. Tier-B stacks already port-offset by N; this isolates
# the shared backing services too.
_slug_hash() { printf '%s' "$1" | cksum | cut -d' ' -f1; }
REDIS_DB_INDEX=$(( $(_slug_hash "$SLUG") % 16 ))
S3_BUCKET_PREFIX="wf-${SAFE_SLUG:0:24}"

case "$CMD" in
  up)
    PLAN_SLUG="${3:?plan-slug (3rd arg)}"
    UI=0; [ "${4:-}" = "--ui" ] && UI=1
    BR="wf/${PLAN_SLUG}/${SLUG}"
    cd "$ROOT"
    git worktree add "$WT" -b "$BR" HEAD || { echo "worktree add failed (branch $BR may exist)" >&2; exit 2; }
    # shared deps the worktree does not inherit
    [ -e "$ROOT/.venv" ] && ln -sfn "$ROOT/.venv" "$WT/.venv"
    [ -e "$ROOT/.env" ]  && ln -sfn "$ROOT/.env"  "$WT/.env"
    if [ "$UI" = "1" ] && [ -d "$ROOT/apps/web-next/node_modules" ]; then
      mkdir -p "$WT/apps/web-next"
      ln -sfn "$ROOT/apps/web-next/node_modules" "$WT/apps/web-next/node_modules"
    fi
    # Per-worktree TEST_DB_NAME (adversarial #4). Write it to .env.worktree (sourced by the agent)
    # AND echo an `export` line so the build/verify prompt can `eval` it. Isolated DB per task.
    {
      echo "# auto-generated by worktree.sh — per-task isolated backing services."
      echo "# Postgres: do NOT share ticket_ocr_test. Redis: own logical DB. S3: own bucket prefix."
      echo "export TEST_DB_NAME=${TEST_DB_NAME}"
      echo "# Redis logical-DB isolation (o3 #8) — agent's conftest should honor REDIS_DB_INDEX if set,"
      echo "# OR rewrite REDIS_URL's trailing /N. Two agents on the same Redis host now use diff DBs."
      echo "export REDIS_DB_INDEX=${REDIS_DB_INDEX}"
      echo "# S3/localstack bucket isolation (o3 #8) — per-task bucket prefix so two UI stacks don't"
      echo "# write the same bucket. conftest/test fixtures should namespace buckets with this."
      echo "export WF_S3_BUCKET_PREFIX=${S3_BUCKET_PREFIX}"
    } > "$WT/.env.worktree"
    # keep symlinks + the worktree env file out of git status
    GITDIR="$(git -C "$WT" rev-parse --git-dir)"
    mkdir -p "$GITDIR/info"
    { echo ".venv"; echo ".env"; echo ".env.worktree"; echo "apps/web-next/node_modules"; } \
      >> "$GITDIR/info/exclude" 2>/dev/null || true
    # Branch-guard override marker — copy ONLY this plan-slug's marker, not every dod-read-* marker
    # (adversarial #15: copying all markers leaks another slug's SDD authorization into this worktree).
    SRC_MARKER="$ROOT/.claude/markers/dod-read-${PLAN_SLUG}.done"
    if [ -f "$SRC_MARKER" ]; then
      mkdir -p "$WT/.claude/markers"
      cp "$SRC_MARKER" "$WT/.claude/markers/dod-read-${PLAN_SLUG}.done" 2>/dev/null || true
    else
      echo ">> NOTE: no override marker dod-read-${PLAN_SLUG}.done in main checkout — lay it first (master infra)." >&2
    fi
    echo "$WT (branch $BR, TEST_DB_NAME=$TEST_DB_NAME, REDIS_DB_INDEX=$REDIS_DB_INDEX, S3_PREFIX=$S3_BUCKET_PREFIX)"
    echo ">> agent must: source ./.env.worktree  (isolated TEST_DB_NAME + REDIS_DB_INDEX + WF_S3_BUCKET_PREFIX)" >&2
    echo ">> commit inside with ALLOW_DIRECT_MAIN=1 (branch_guard false-fires on worktrees)" >&2
    ;;
  down)
    FORCE=0; [ "${3:-}" = "--force" ] && FORCE=1
    cd "$ROOT"
    if [ ! -d "$WT" ]; then echo "no worktree at $WT" >&2; exit 0; fi
    BR="$(git -C "$WT" rev-parse --abbrev-ref HEAD 2>/dev/null)"
    # GUARDED teardown (adversarial #6: the old `remove --force` + `branch -D` silently destroyed
    # unmerged/dirty/unpushed task work). Refuse unless safe — OR snapshot a bundle first.
    if [ "$FORCE" != "1" ]; then
      DIRTY="$(git -C "$WT" status --porcelain 2>/dev/null | grep -vE '\.env|\.venv|node_modules|markers/dod-read' || true)"
      if [ -n "$DIRTY" ]; then
        echo "REFUSING down: worktree $WT has uncommitted changes:" >&2
        echo "$DIRTY" >&2
        echo "  commit them, or re-run with --force (LOSES them)." >&2
        exit 3
      fi
      # is the branch's tip reachable from the feature branch (i.e. merged)? infer feat from BR prefix.
      FEAT="${BR#wf/}"; FEAT="feat/${FEAT%%/*}"
      TIP="$(git -C "$WT" rev-parse HEAD 2>/dev/null)"
      if git rev-parse --verify "$FEAT" >/dev/null 2>&1; then
        if ! git merge-base --is-ancestor "$TIP" "$FEAT" 2>/dev/null; then
          # not merged → snapshot a recoverable bundle before any deletion
          BUNDLE="$ROOT/.worktree-snapshots"; mkdir -p "$BUNDLE"
          git -C "$ROOT" bundle create "$BUNDLE/${SLUG}-${TIP:0:8}.bundle" "$BR" 2>/dev/null \
            && echo ">> $BR not merged into $FEAT — snapshotted to $BUNDLE/${SLUG}-${TIP:0:8}.bundle" >&2
          echo "REFUSING down: $BR ($TIP) is NOT merged into $FEAT. Bundle saved. Re-run --force to discard." >&2
          exit 3
        fi
      else
        echo ">> WARN: can't find $FEAT to verify merge; snapshotting before delete." >&2
        BUNDLE="$ROOT/.worktree-snapshots"; mkdir -p "$BUNDLE"
        git -C "$ROOT" bundle create "$BUNDLE/${SLUG}-${TIP:0:8}.bundle" "$BR" 2>/dev/null || true
      fi
    fi
    git worktree remove --force "$WT" 2>/dev/null || echo "worktree remove failed for $WT" >&2
    [ -n "${BR:-}" ] && [ "$BR" != "HEAD" ] && git branch -D "$BR" 2>/dev/null || true
    echo "removed $WT (branch $BR)"
    ;;
  path)
    echo "$WT"
    ;;
  testdb)
    echo "$TEST_DB_NAME"
    ;;
  *) echo "unknown cmd: $CMD" >&2; exit 2;;
esac
